"""
reporter.py — generate a markdown log of everything CleanWave did
"""
from __future__ import annotations

import datetime
from pathlib import Path

from .models import MoveRecord, SkippedDir


def _size_str(path: Path) -> str:
    try:
        b = path.stat().st_size if path.exists() else 0
    except OSError:
        b = 0
    for unit in ("B", "KB", "MB", "GB"):
        if b < 1024:
            return f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} TB"


def generate_report(
    moved: list[MoveRecord],
    skipped_dirs: list[SkippedDir],
    scan_dirs: list[str],
    duration: float,
    output_path: Path,
    dry_run: bool = False,
) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    deletion = [m for m in moved if "deletion_approval" in str(m.destination)]
    old       = [m for m in moved if "OLD_FILES" in str(m.destination)]

    mode_note = " *(dry run — no files were actually moved)*" if dry_run else ""

    lines = [
        f"# CleanWave Report{mode_note}",
        f"",
        f"**Date:** {now}  ",
        f"**Duration:** {duration:.1f}s  ",
        f"**Scanned:** {', '.join(scan_dirs)}  ",
        f"",
        f"## Summary",
        f"",
        f"| Category | Count |",
        f"|---|---|",
        f"| Moved to `deletion_approval/` | {len(deletion)} |",
        f"| Moved to `OLD_FILES/` | {len(old)} |",
        f"| Directories skipped (OS/app) | {len(skipped_dirs)} |",
        f"",
    ]

    # ── deletion_approval section ─────────────────────────────────────────
    if deletion:
        lines += [
            "## 🗑️ deletion_approval",
            "",
            "| Original path | Moved to | Category | Reason |",
            "|---|---|---|---|",
        ]
        for m in deletion:
            lines.append(
                f"| `{m.original}` | `{m.destination.name}` "
                f"| {m.category} | {m.reason} |"
            )
        lines.append("")

    # ── OLD_FILES section ─────────────────────────────────────────────────
    if old:
        lines += [
            "## 📦 OLD_FILES",
            "",
            "| Original path | Moved to | Reason |",
            "|---|---|---|",
        ]
        for m in old:
            lines.append(
                f"| `{m.original}` | `{m.destination.name}` | {m.reason} |"
            )
        lines.append("")

    # ── Skipped directories ───────────────────────────────────────────────
    if skipped_dirs:
        lines += [
            "## ⚠️ Skipped Directories",
            "",
            "These were identified as OS or app-related and not recursed into.  ",
            "Review manually if needed.",
            "",
            "| Path | Reason |",
            "|---|---|",
        ]
        for sd in skipped_dirs:
            lines.append(f"| `{sd.path}` | {sd.reason} |")
        lines.append("")

    lines += [
        "---",
        "*Generated by CleanWave — review everything before permanent deletion.*",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
