"""
reporter.py — markdown report + JSON sidecar for undo support
"""
from __future__ import annotations

import datetime
import json
from pathlib import Path

from .models import MoveRecord, SkippedDir


def generate_report(
    moved: list[MoveRecord],
    skipped_dirs: list[SkippedDir],
    scan_dirs: list[str],
    duration: float,
    output_path: Path,
    dry_run: bool = False,
) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    deletion = [m for m in moved if "deletion_approval" in str(m.destination)]
    old       = [m for m in moved if "OLD_FILES" in str(m.destination)]

    mode_note = " *(dry run — no files were actually moved)*" if dry_run else ""

    lines = [
        f"# CleanWave Report{mode_note}",
        "",
        f"**Date:** {now}  ",
        f"**Duration:** {duration:.1f}s  ",
        f"**Scanned:** {', '.join(scan_dirs)}  ",
        "",
        "## Summary",
        "",
        "| Category | Count |",
        "|---|---|",
        f"| Moved to `deletion_approval/` | {len(deletion)} |",
        f"| Moved to `OLD_FILES/` | {len(old)} |",
        f"| Directories skipped (OS/app) | {len(skipped_dirs)} |",
        "",
    ]

    if deletion:
        lines += [
            "## 🗑️ deletion_approval",
            "",
            "| Original path | Moved to | Category | Reason |",
            "|---|---|---|---|",
        ]
        for m in deletion:
            lines.append(
                f"| `{m.original}` | `{m.destination}` | {m.category} | {m.reason} |"
            )
        lines.append("")

    if old:
        lines += [
            "## 📦 OLD_FILES",
            "",
            "| Original path | Moved to | Reason |",
            "|---|---|---|",
        ]
        for m in old:
            lines.append(
                f"| `{m.original}` | `{m.destination}` | {m.reason} |"
            )
        lines.append("")

    if skipped_dirs:
        lines += [
            "## ⚠️ Skipped Directories",
            "",
            "These were identified as OS or app-related and not recursed into.",
            "",
            "| Path | Reason |",
            "|---|---|",
        ]
        for sd in skipped_dirs:
            lines.append(f"| `{sd.path}` | {sd.reason} |")
        lines.append("")

    lines += [
        "---",
        "*Generated by CleanWave — review everything before permanent deletion.*",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    # ── JSON sidecar for --undo ───────────────────────────────────────────
    # Only written for real runs (not dry-run) since no files actually moved.
    if not dry_run and moved:
        sidecar = [
            {"original": str(m.original), "moved_to": str(m.destination)}
            for m in moved
        ]
        sidecar_path = output_path.with_suffix(".json")
        sidecar_path.write_text(json.dumps(sidecar, indent=2), encoding="utf-8")
